// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_310_W22SD_Assignment.Models;

#nullable disable

namespace SD_310_W22SD_Assignment.Migrations
{
    [DbContext(typeof(MyTunesMichaelContext))]
    [Migration("20220724233654_AddWalletAndPrice")]
    partial class AddWalletAndPrice
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("UserId");

                    b.ToTable("Song", (string)null);
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Wallet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("FK_Song_Artist");

                    b.HasOne("SD_310_W22SD_Assignment.Models.User", "User")
                        .WithMany("Songs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Song_User");

                    b.Navigation("Artist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.User", b =>
                {
                    b.HasOne("SD_310_W22SD_Assignment.Models.Song", "Song")
                        .WithMany("Users")
                        .HasForeignKey("SongId")
                        .HasConstraintName("FK_User_Song");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.Song", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SD_310_W22SD_Assignment.Models.User", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
